### ISSUE TITLE
question: CSV

### ISSUE THREAD

**Issue by joeblew99** [gocraft/health#15]
i am logging JSON and sending to Bugsnap for now. All great.

But for the business analytics, i need to log as CSV and send up to S3.

**Comment by cypriss** [comment]
@joeblew99 It would be fairly simple to write your own sink that emits CSV to S3. I don't think it would make sense as part of the core health package -- it seems rather custom.

**Comment by joeblew99** [comment]
Ok thanks for the feedback.
I will have a look
